
services:
  db:
    image: postgres:16
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - ecommerce_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - ecommerce_net

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - ecommerce_net

  app:
    build: .
    container_name: ecommerce_api
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASS: admin
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    networks:
      - ecommerce_net
    restart: always

  worker:
    build: .
    container_name: ecommerce_worker
    command: celery -A worker worker --loglevel=info
    depends_on:
      - redis
      - app
    networks:
      - ecommerce_net

  nginx:
    image: nginx:latest
    container_name: ecommerce_nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  db_data:
